# 多通路解析配置
# 每增加一路，就加一个 - 开头的配置块

# 可以继续添加更多通路
  # - name: 名称
  #   domain: 域名
  #   dns: 8.8.8.8
  #   ecs: 14.153.0.0/24
  #   count: 输出数量
  
routes:
  - name: qms_ct
    domain: ct.877774.xyz
    dns: 8.8.8.8
    ecs: 14.153.0.0/24
    count: 3

  - name: qms_na
    domain: na.877774.xyz
    dns: 8.8.8.8
    ecs: 14.153.0.0/24
    count: 3
