# 多通路解析配置
# 每增加一路，就加一个 - 开头的配置块

routes:
  - name: qms_ct                    # 通路名称（会生成 ips-ct）
    domain: ct.877774.xyz
    dns: 8.8.8.8
    ecs: 14.153.0.0/24
    count: 2                    # 最多输出几个 IP

  - name: qms_na               # 示例第二路，可自行增加/删除
    domain: na.877774.xyz
    dns: 8.8.8.8
    ecs: 14.153.0.0/24
    count: 2
